### ISSUE TITLE
Crear una vista de Login

### ISSUE THREAD

**Issue by leonardoo** [DjangoQuilla/temii#22]
Cuando se hacen las test para comprobar si el usuario esta logueado, este invoca a la vista de LOGIN_URL, pero al esta no estar implementada produce un error implica #21 #20

**Comment by Scot3004** [comment]
Esta vista, debe ser con el issue #11 resuelto, o basta con implementar la de django admin o algun login básico?

**Comment by leonardoo** [comment]
No se puede usar el login del admin, debe ser del proyecto

**Comment by leonardoo** [comment]
Esto no creó que tenga que ver nada con el #11 aún necesitamos algo rápido para corregir ese error

**Comment by javierdaza** [comment]
El issue #11 trata sobre la integracion con el API de meetup. Eso lo podemos resolver despues. 

Aunque creo que podemos usar la integracion a **Meetup** que ya trae el [django-hackaton-starter Boilerplate](https://github.com/DrkSephy/django-hackathon-starter) de una vez????
