### ISSUE TITLE
Icono Votos en vista detalle charla

### ISSUE THREAD

**Issue by javierdaza** [DjangoQuilla/temii#37]
Deberia poder verse en el detalle de cada charla:

- [ ] El icono de votos con el conteo de los mismos

Debe quedar parecida a [esta plantilla](http://www.one-click-forum.com/live-preview/discussion/2/welcome-to-the-one-click-premium-vanilla-theme), con excepcion de los adicionales como los votos, etiquetas, etc.

Dejo imagen de referencia:

![temii-votacion-detalle](https://cloud.githubusercontent.com/assets/3085051/14930489/d3be2056-0e29-11e6-97d2-017e8cc82e1e.jpg)

**Comment by Scot3004** [comment]
consultare, eso de la imagen puede ser con gravatar?

**Comment by javierdaza** [comment]
mmmmm es que la foto del tallerista se obtendra de su perfil en meetup (recuerda que la integracion con la API de meetup no esta terminada :( )

Este issue mas que todo es tipo front-end, acomodar bien los template tags en Django, el diseño y eso. Vas a trabajar en este issue @Scot3004 ??

**Comment by Scot3004** [comment]
En otras palabras hay que concluir la integración con meetup para cortar esta

**Comment by javierdaza** [comment]
No necesariamente, pues esto seria solo CSS y HTML. Puede ir por separado, solo necesitamos saber en que posicion ubicar la foto y cosas asi
