### ISSUE TITLE
README de como colocar la credencial de github para loguearse

### ISSUE THREAD

**Issue by Scot3004** [DjangoQuilla/temii#44]
Para desarrolladores novatos que quieran deployar una copia local del proyecto

**Comment by javierdaza** [comment]
Disculpa, el login con github se implementó para pasar el test pero no será el login definitivo. Documentaré esto cuando este la integración del API de meetup con python-social-auth. Por lo pronto mira las comentarios que deje en el settings.py sobre las credenciales.
