### ISSUE TITLE
Seleccionar Categorías

### ISSUE THREAD

**Issue by javierdaza** [DjangoQuilla/temii#5]
Dado el nuevo CSS, que aparezca el select para poder escoger la categoría de la charla a postular. Esto es en la vista registrar_charla

**Comment by Scot3004** [comment]
Este issue tengo la respuesta, elaborando parches a partir de los cambios

**Comment by Guzman-D-Dario** [comment]
Ya lo corregí, pero estoy haciendo algunas cosas mas ya luego mando el pull request.
