### ISSUE TITLE
Test para comprobar queryset charlas

### ISSUE THREAD

**Issue by javierdaza** [DjangoQuilla/temii#54]
Este test debe comprobar que efectivamente los queryset de las charlas envien objetos de dicha categoría.

- [ ] Charlas posibles
- [ ] Charlas agendadas
- [ ] Charlas finalizadas

Este issue fue creado también para evitar bugs como el del issue #55

**Comment by leonardoo** [comment]
los queryset se encuentran bn dado las test del pr #56
