### ISSUE TITLE
CSS para tags en vista detalle charla

### ISSUE THREAD

**Issue by javierdaza** [DjangoQuilla/temii#68]
- [ ] Las etiquetas de las categorias con el CSS de materializecss

Debe quedar parecida a [esta plantilla](http://www.one-click-forum.com/live-preview/discussion/2/welcome-to-the-one-click-premium-vanilla-theme), con excepcion de los adicionales como los votos, etiquetas, etc.

Sería un estilo **algo parecido** a las etiquetas que usa StackOverFlow. Dejo esta imagen de referencia

![etiquetas-temii](https://cloud.githubusercontent.com/assets/3085051/14930463/a5f84ff2-0e29-11e6-94d7-764fff6adeea.jpg)

**Comment by Scot3004** [comment]
lo hare usando [Chips](http://materializecss.com/chips.html)
