### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by javierdaza** [DjangoQuilla/temii#7]
Realizar deployment en servidor de producción

**Comment by panchicore** [comment]
Donde se va a deployar?

**Comment by javierdaza** [comment]
Vamos a empezar con la versión gratuita de Heroku

**Comment by javierdaza** [comment]
Cerrado por PR https://github.com/DjangoQuilla/temii/pull/58 y commit 52f5305c6c512a0b6de24cfd7dcfaa5d43a805b9
